CREATE DATABASE DOCE_SAEP_DB;

USE DOCE_SAEP_DB;

CREATE TABLE USUARIO (
    USUARIO_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255) UNIQUE,
    SENHA VARCHAR(255)
);

CREATE TABLE DOCE (
    DOCE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    FORMATO VARCHAR(255),
    TAMANHO VARCHAR(255),
    MARCA VARCHAR(255),
    TIPO VARCHAR(255),
    DATA_VALIDADE DATE,
    FK_USUARIO_ID INTEGER
);

CREATE TABLE LOGS (
    LOG_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    LOG_DESCRICAO VARCHAR(255),
    LOG_DATA_HORA DATE
);

CREATE TABLE ESTOQUE (
    ESTOQUE_ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    ESTOQUE_QUANTIDADE INTEGER,
    FK_DOCE_ID INTEGER 
);
 
ALTER TABLE DOCE ADD CONSTRAINT FK_DOCE_2
    FOREIGN KEY (FK_USUARIO_ID)
    REFERENCES USUARIO (USUARIO_ID);
 
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ESTOQUE_2
    FOREIGN KEY (FK_DOCE_ID)
    REFERENCES DOCE (DOCE_ID);

INSERT INTO USUARIO (NOME, EMAIL, SENHA)
VALUES				("Luan", "luan@email.com", "123456789"),
					("Liebert", "liebert@emial.com", "987654321"),
                    ("Caua", "caua@email.com", "24681012");
                    
INSERT INTO DOCE (FORMATO, TAMANHO, MARCA, TIPO, DATA_VALIDADE, FK_USUARIO_ID)
VALUES			 ("quadrado", "pequeno", "Nestlé", "chocolate", "2025-12-31", 1),
				 ("redondo", "médio", "Garoto", "bala", "2026-03-15", 1),
                 ("cilíndrico", "grande", "Fini", "goma", "2025-09-10", 1);
                 
INSERT INTO ESTOQUE (ESTOQUE_QUANTIDADE, FK_DOCE_ID)
VALUES 				(5,1),
					(10,2),
                    (20,3);
                 